blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://server.liupurnomo.com/docs
    about: Check out the API documentation for usage guides and examples

  - name: GitHub Discussions
    url: https://github.com/liu-purnomo/server.liupurnomo.com/discussions
    about: Ask questions and discuss ideas with the community

  - name: Email Support
    url: mailto:liu@drone.co.id
    about: Contact the maintainer directly for sensitive issues or private inquiries
