name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees:
  - liu-purnomo

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and Setup
        - Configuration
        - Usage and Implementation
        - API Endpoints
        - Database and Prisma
        - Authentication
        - Deployment
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question
      placeholder: |
        What are you trying to achieve?
        What have you tried so far?

  - type: textarea
    id: code
    attributes:
      label: Relevant Code (if applicable)
      description: Share any relevant code snippets
      render: typescript
      placeholder: Paste your code here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any additional details...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true
        - label: I have provided sufficient context above
          required: true
